formulated human readalbe

diff --git a/Advanced_shell/data_extraction_automation-0x01 b/Advanced_shell/data_extraction_automation-0x01
--- a/Advanced_shell/data_extraction_automation-0x01
+++ b/Advanced_shell/data_extraction_automation-0x01
@@ -1,5 +1,12 @@
 #!/bin/bash
-INPUT_FILE=data.json
+
+INPUT_FILE="data.json"
+
+if [[ ! -f "$INPUT_FILE" ]]; then
+    echo "Error: $INPUT_FILE not found"
+    exit 1
+fi
+
 
 NAME=$(jq -r '.name' "$INPUT_FILE" | sed 's/\b\(.\)/\u\1/')
 
